"""empty message

Revision ID: 97762c3bffae
Revises: c00fad32c19f
Create Date: 2022-11-02 21:57:50.670138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97762c3bffae'
down_revision = 'c00fad32c19f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('register')
    # ### end Alembic commands ###
